modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/pau101/Low-Health/issues"
[[mods]]
    modId="lowhealth"
    version="${version}"
    displayName="Low Health"
    displayURL="https://minecraft.curseforge.com/projects/low-health"
    authors="pau101"
    description="The Low Health mod adds configurable effects for when the player is low health."
[[dependencies.lowhealth]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lowhealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"
